application: zipcode-ja-python-gae
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Remote API
builtins:
- remote_api: on

handlers:
# Static assets
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Endpoints handler
- url: /_ah/spi/.*
  script: app.api.APPLICATION

libraries:
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: "1.0"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[cod]$
- ^(.*/)?\..*$
- ^(.*/)?.DS_Store$
- ^README.md$
- ^ .gitignore$
- ^.idea/
- ^KEN_ALL.CSV$
- ^bulkloader.yaml$
- ^bulkloader-.*$
- ^requirements\.txt
